spring:
    profiles: dev
server:
    port: 8000
    datasource:
        driver-class-name: org.postgresql.Driver
        password: changemeinprod!
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                globally_quoted_identifiers: true
        show-sql: true
    management:
        endpoints:
            web:
                exposure:
                    include: *
        endpoint:
            health:
                roles: USER
            show-details: when_authorized
---
spring:
    profiles: dev
server:
    port: 9000
    datasource:
        driver-class-name: org.h2.Driver
        password: password
        url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
        username: sa
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                globally_quoted_identifiers: true
        show-sql: true
